const:
  default-page-size: 20

file:
  directory: D:\GSY\GreenGramVer3\greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: studyspringbootadfadfasdfasdfadsfadfadsfasdfweqerqewrdfasdf11111111

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer2
  datasource:
     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
     url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
     username: root
     password: green502
  jackson:
    default-property-inclusion: non_null #응담 JSON을 만들 때 null인 속성은 제외한다.

  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
